# .streamlit/secrets.toml

[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "mspr_db"
username = "postgres"
password = "ibrahima"

[filename]
table_1 = "turbine"
table_2 = "sensor_inventory"
table_3 = "raw_measurements"
csv = "production"
